import React, { useState } from 'react';

const InfoSection = ({ defaultExpanded = false }) => {
  const [showInfo, setShowInfo] = useState(defaultExpanded);

  return (
    <div className="info-section">
      <button 
        onClick={() => setShowInfo(!showInfo)}
        className="info-toggle"
      >
        {showInfo ? 'Hide Info' : 'What is this?'} 
        <span className={`arrow ${showInfo ? 'up' : 'down'}`}>▼</span>
      </button>
      
      {showInfo && (
        <div className="info-content">
          <h3>About Socratic Restructuring</h3>
          <p>This tool helps you challenge negative thoughts using <strong>Socratic Questioning</strong>, a technique from Cognitive Behavioral Therapy (CBT).</p>
          
          <h4>How to use it</h4>
          <ol>
            <li><strong>Identify a negative thought</strong> that is causing you distress.</li>
            <li><strong>Analyze it</strong> by identifying thinking errors (cognitive distortions).</li>
            <li><strong>Examine the evidence</strong> for and against this thought.</li>
            <li><strong>Receive a balanced thought</strong> generated by AI based on your inputs.</li>
          </ol>

          <h4>When to use it</h4>
          <p>Use this whenever you feel overwhelmed, anxious, or stuck in a loop of negative thinking. It helps break the cycle by engaging your analytical mind.</p>

          <h4>Privacy & Data</h4>
          <p>Your data is stored <strong>locally on your machine</strong>, so you don't need to worry about others seeing your submissions. Because of this, clearing your browser data may wipe out your history. A future version will allow for backups and restore.</p>

          <p className="info-footer"><em>Based on worksheets and concepts from <a href="https://www.therapistaid.com" target="_blank" rel="noopener noreferrer">TherapistAid.com</a>. AI analysis is generated using Google Gemini.</em></p>
        </div>
      )}
    </div>
  );
};

export default InfoSection;